const {spawn}=require('child_process'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {S3Client,PutObjectCommand}=require('@aws-sdk/client-s3');
const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is required');
const dir=process.env.BACKUP_DIR||path.join(__dirname,'..','backups');fs.mkdirSync(dir,{recursive:true});
const stamp=new Date().toISOString().replace(/[:.]/g,'-');const raw=path.join(dir,`ember-vault-${stamp}.dump`),out=process.env.BACKUP_ENCRYPTION_KEY?raw+'.enc':raw;
const p=spawn('pg_dump',['--format=custom','--no-owner','--no-acl','--file',raw,url],{stdio:'inherit'});
p.on('exit',async code=>{if(code){try{fs.unlinkSync(raw)}catch{}process.exit(code)}try{let uploadFile=raw;if(process.env.BACKUP_ENCRYPTION_KEY){const key=Buffer.from(process.env.BACKUP_ENCRYPTION_KEY,'base64');if(key.length!==32)throw new Error('BACKUP_ENCRYPTION_KEY must be base64 for 32 bytes');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(fs.readFileSync(raw)),cipher.final()]),tag=cipher.getAuthTag();fs.writeFileSync(out,Buffer.concat([Buffer.from('EVB1'),iv,tag,data]));fs.unlinkSync(raw);uploadFile=out}
if(process.env.BACKUP_S3_BUCKET){const client=new S3Client({region:process.env.AWS_REGION||'us-east-1',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true'});await client.send(new PutObjectCommand({Bucket:process.env.BACKUP_S3_BUCKET,Key:`ember-vault/${path.basename(uploadFile)}`,Body:fs.createReadStream(uploadFile),ContentType:'application/octet-stream',ServerSideEncryption:process.env.S3_SSE||undefined}));console.log('Uploaded backup to object storage.');}
const files=fs.readdirSync(dir).filter(x=>x.startsWith('ember-vault-')).sort(),keep=Number(process.env.BACKUP_RETENTION||14);for(const f of files.slice(0,Math.max(0,files.length-keep)))try{fs.unlinkSync(path.join(dir,f))}catch{}console.log('Backup written:',uploadFile)}catch(e){console.error(e);process.exit(1)}});
